#ifndef D_NUCLEOL432KC
#define D_NUCLEOL432KC
#include "stm32l4xx.h"
/*
 * Buttons and LEDs on NUCLEO Board.
 */

/*
 * MCO OUTPUT
 */
#define NUCLEO_MCO_RCC_CLK_REG AHB2ENR
#define NUCLEO_MCO_RCC_CLK_BIT RCC_AHB2ENR_GPIOAEN
#define NUCLEO_MCO_PORT_GPIOA GPIOA
#define NUCLEO_MCO_PIN_MODE_ZERO GPIO_MODER_MODE8
#define NUCLEO_MCO_PIN_MODE_ALT GPIO_MODER_MODE8_1
#define NUCLEO_MCO_SPEED_BIT_MASK GPIO_OSPEEDER_OSPEEDR8 //should be 0b11
#define NUCLEO_MCO_PIN_ALT_FUNC_REG AFRH
#define NUCLEO_MCO_PIN_ALT_FUNC_BIT_MASK GPIO_AFRH_AFRH0 //should be zeroed, set as default
/*
#define NUCLEO_BUTTON_IOPENER_BIT RCC_IOPENR_GPIOCEN // Bit for clk for GPIOC enabling.
#define NUCLEO_BUTTON_PORT GPIOC
#define NUCLEO_BUTTON_PIN 0x0D
#define NUCLEO_BUTTON_PIN_MASK 1 << NUCLEO_BUTTON_PIN
*/
/*
#define NUCLEO_LED_GREEN_IOPENER_BIT RCC_IOPENR_GPIOAEN // Bit for clk for GPIOA enabling.
#define NUCLEO_LED_GREEN_PORT GPIOA
#define NUCLEO_LED_GREEN_PIN 0x05
#define NUCLEO_LED_GREEN_PIN_MASK 1 << NUCLEO_LED_GREEN_PIN
*/
/*
#define NUCLEO_USART2_PORT GPIOA
#define NUCLEO_USART2_PIN_TX 0x02
#define NUCLEO_USART2_PIN_RX 0x03
#define NUCLEO_USART2_PIN_TX_MASK 1 << NUCLEO_USART2_PIN_TX
#define NUCLEO_USART2_PIN_RX_MASK 1 << NUCLEO_USART2_PIN_RX
#define NUCLEO_USART2_ALT_FUNC	4ul
#define NUCLEO_USART2_IOPENER_BIT RCC_IOPENR_GPIOAEN // Bit for clk for GPIOA enabling.
*/

#endif //D_NUCLEOL432KC
