#include "user.h"

void mcoOutputPinEnable(void) {
	RCC->NUCLEO_MCO_RCC_CLK_REG |= NUCLEO_MCO_RCC_CLK_BIT;
	NUCLEO_MCO_PORT_GPIOA->MODER &= ~(NUCLEO_MCO_PIN_MODE_ZERO);
	NUCLEO_MCO_PORT_GPIOA->MODER |= NUCLEO_MCO_PIN_MODE_ALT;
	NUCLEO_MCO_PORT_GPIOA->OSPEEDR |= NUCLEO_MCO_SPEED_BIT_MASK;
}
