#include "user.h"

void mcoOutputPinEnable(void) {
	RCC->NUCLEO_MCO_RCC_CLK_REG |= NUCLEO_MCO_RCC_CLK_BIT;
	NUCLEO_MCO_PORT_GPIOA->MODER &= ~(NUCLEO_MCO_PIN_MODE_ZERO);
	NUCLEO_MCO_PORT_GPIOA->MODER |= NUCLEO_MCO_PIN_MODE_ALT;
	NUCLEO_MCO_PORT_GPIOA->OSPEEDR |= NUCLEO_MCO_SPEED_BIT_MASK;
}

void ledGreenConfig(void) {
	RCC->NUCLEO_LED_GREEN_RCC_CLK_REG |= NUCLEO_LED_GREEN_RCC_CLK_BIT;
	NUCLEO_LED_GREEN_PORT_GPIOB->MODER &= ~(NUCLEO_LED_GREEN_PIN_MODE_ZERO);
	NUCLEO_LED_GREEN_PORT_GPIOB->MODER |= NUCLEO_LED_GREEN_PIN_MODE_OUT;
}

void ledGreen(char onOff) {
	NUCLEO_LED_GREEN_PORT_GPIOB->ODR = (NUCLEO_LED_GREEN_PORT_GPIOB->ODR & (~NUCLEO_LED_GREEN_PIN_MASK)) | (onOff ? NUCLEO_LED_GREEN_PIN_MASK : 0);
}

void ledGreenToggle(void) {
	NUCLEO_LED_GREEN_PORT_GPIOB->ODR ^= NUCLEO_LED_GREEN_PIN_MASK;
}
